name: CI
on:
  push:
    paths-ignore:
      - doc/**
      - README.md
      - LICENSE
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew testDebugUnitTest
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            **/build/reports/tests/**/*
            **/build/reports/test-results/**/*
          if-no-files-found: warn
          retention-days: 14

  build:
    if: ${{ (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: debug_apk
          path: |
            app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 7

  deploy:
    if: ${{ github.ref == 'refs/heads/develop' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    needs: [test, build]
    timeout-minutes: 10
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: debug_apk
          path: downloaded
      - name: Upload to DeployGate
        run: |
          APK_PATH=app-debug.apk
          TIME=$(date "+%Y%m%d_%H%M%S")
          GITHUB_SHA=${{ github.sha }}
          COMMIT_HASH=$(echo ${GITHUB_SHA} | cut -c 1-8)
          USERNAME=${{ vars.USERNAME }}
          DEPLOYGATE_API_KEY=${{ secrets.DEPLOYGATE_API_KEY }}
          curl -F "file=@downloaded/${APK_PATH}" -F "token=${DEPLOYGATE_API_KEY}" -F "message=Build by GitHub Actions <${COMMIT_HASH}> (${TIME})" https://deploygate.com/api/users/${USERNAME}/apps
